-- Baseline Schema: Core tables for Donation Mentoring
-- This is the foundation schema before auth was added

-- ============================================
-- MENTORS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS public.mentors (
    id UUID DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    name_en VARCHAR(255) NOT NULL,
    name_ko VARCHAR(255) NOT NULL,
    position_en TEXT,
    position_ko TEXT,
    company_en TEXT,
    company_ko TEXT,
    location_en VARCHAR(255) NOT NULL,
    location_ko VARCHAR(255) NOT NULL,
    description_en TEXT NOT NULL,
    description_ko TEXT NOT NULL,
    picture_url TEXT,
    linkedin_url TEXT,
    calendly_url TEXT,
    email TEXT,
    languages TEXT[],
    tags JSONB DEFAULT '[]'::jsonb,
    session_time_minutes INTEGER,
    session_price_usd NUMERIC(10,2),
    display_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Indexes for mentors
CREATE INDEX IF NOT EXISTS idx_mentors_active ON public.mentors(is_active);
CREATE INDEX IF NOT EXISTS idx_mentors_created_at ON public.mentors(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_mentors_display_order ON public.mentors(display_order);
CREATE INDEX IF NOT EXISTS idx_mentors_email ON public.mentors(email);

-- ============================================
-- REVIEWS TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS public.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review VARCHAR,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- ============================================
-- APP CONFIG TABLE
-- ============================================
CREATE TABLE IF NOT EXISTS public.app_config (
    key TEXT NOT NULL PRIMARY KEY,
    value TEXT NOT NULL
);

-- ============================================
-- LEGACY ADMINS TABLE (kept for backwards compatibility)
-- ============================================
CREATE TABLE IF NOT EXISTS public.admins (
    id UUID DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    password TEXT,
    reset_token TEXT,
    reset_token_expires TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- UPDATED_AT TRIGGER FUNCTION
-- ============================================
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger for mentors updated_at
DROP TRIGGER IF EXISTS update_mentors_updated_at ON public.mentors;
CREATE TRIGGER update_mentors_updated_at
    BEFORE UPDATE ON public.mentors
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ============================================
-- ROW LEVEL SECURITY
-- ============================================
ALTER TABLE public.mentors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;

-- Mentor policies (permissive - will be tightened later)
CREATE POLICY "Anyone can view active mentors" ON public.mentors
    FOR SELECT USING (is_active = true);

CREATE POLICY "Authenticated users can view all mentors" ON public.mentors
    FOR SELECT TO authenticated USING (true);

CREATE POLICY "Authenticated users can insert mentors" ON public.mentors
    FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Authenticated users can update mentors" ON public.mentors
    FOR UPDATE TO authenticated USING (true);

CREATE POLICY "Authenticated users can delete mentors" ON public.mentors
    FOR DELETE TO authenticated USING (true);

-- Reviews policies
CREATE POLICY "Anyone can view reviews" ON public.reviews
    FOR SELECT USING (true);

CREATE POLICY "Anyone can insert reviews" ON public.reviews
    FOR INSERT WITH CHECK (true);

-- ============================================
-- GRANTS
-- ============================================
GRANT SELECT ON public.mentors TO anon;
GRANT ALL ON public.mentors TO authenticated;
GRANT ALL ON public.mentors TO service_role;

GRANT SELECT, INSERT ON public.reviews TO anon;
GRANT ALL ON public.reviews TO authenticated;
GRANT ALL ON public.reviews TO service_role;

GRANT ALL ON public.app_config TO service_role;
GRANT ALL ON public.admins TO service_role;
